### PR TITLE
Issue 49

### PR DESCRIPTION
**Pull request by qkraudghgh**
#49

### CODE REVIEW

**Comment by mingrammer** [comment]
Please use capital-case on commit message later :|

**Review by mingrammer — COMMENTED** [review]
Resolve the conflicts please.

**Comment by qkraudghgh** [comment]
@mingrammer 
OK, I amend my commits and push -f
more, I rewrite create.js in es6, 
and change indent 4 to 2

**Review by mingrammer — APPROVED** [review]
LGTM +1

**Pull request merged**
