### PR TITLE
Add foundation framework

### PR DESCRIPTION
**Pull request by kyunooh**
Add foundation framework static files 
#8

### CODE REVIEW

**Review by mingrammer — COMMENTED** [review]
What are `app.css` and `app.js` for?

**Review by getogrand — CHANGES_REQUESTED** [review]
Please locate 3rd party libraries into `warp/static/vendor/{library_name}/`.

**Comment by mingrammer** [comment]
I think that we need only `*.min.*` files. `foundation.js` and `foundation.css` are required for us?

**Comment by kyunooh** [comment]
app.css and app.js is not added by me. they are included in default foundation. That seems be for customizing. and not compressed files are needed too to debug when something is wrong.
We will  just remove script code on production level :D

**Comment by getogrand** [comment]
We'll use django-compressor which is dependency of cookie-cutter-django.
Django-compressor will minifiy the css/js files so that *.min file is not required I think.

**Review by getogrand — APPROVED** [review]

**Pull request merged**
